//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSchedule.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules
    {
        public int SchedulesId { get; set; }
        public string AppId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string MobileNo { get; set; }
        public bool IsValid { get; set; }
        public string Reason { get; set; }
        public string Response { get; set; }
        public System.DateTime EventDate { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public bool IsSent { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
    }
}
